function fancyplot(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 07-Feb-2020 17:11:08

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

X1 = linspace(-1/2, 1/2, length(tx_waveform));
YMatrix1=[20*log10(filtfilt(1./(20*ones(1,20)),1,abs(fftshift(fft(tx_waveform, length(tx_waveform))))));...
   20*log10(filtfilt(1./(20*ones(1,20)),1,abs(fftshift(fft(rx_signal_post_channel, length(rx_signal_post_channel)))))); ...
   20*log10(filtfilt(1./(20*ones(1,20)),1,abs(fftshift(fft(channel_response, length(tx_waveform)))))); ...
   20*log10(filtfilt(1./(20*ones(1,20)),1,abs(fftshift(fft(equalizer_coefficients, length(tx_waveform)))))); ...
   20*log10(filtfilt(1./(20*ones(1,20)),1,abs(fftshift(fft(rx_signal_post_equalization, length(rx_signal_post_equalization))))))];

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1);
set(plot1(1),'DisplayName','System Input','LineWidth',1,...
   'Color',[0.850980401039124 0.325490206480026 0.0980392172932625]);
set(plot1(2),'DisplayName','System Without equalization',...
   'Color',[0.494117647409439 0.184313729405403 0.556862771511078]);
set(plot1(3),'DisplayName','Channel Response',...
   'Color',[0.749019622802734 0.749019622802734 0]);
set(plot1(4),'DisplayName','Equalizer Response');
set(plot1(5),'DisplayName','System With equalization','LineStyle','--',...
   'Color',[0 0.498039215803146 0]);

% Create ylabel
ylabel('Power Spectral Density (dB)','FontName','Times New Roman');

% Create xlabel
xlabel('F/Fs','FontName','Times New Roman');

% Create title
title('Power Spectrum');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-0.5 0.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-30.0274129164846 74.9725870835154]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontName','Times New Roman','XGrid','on','XTick',...
   [-0.5 -0.375 -0.25 -0.125 0 0.125 0.25 0.375 0.5],'YGrid','on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
   'Position',[0.622484815058252 0.770732874248285 0.27842564989457 0.145873316533277]);

